[package]
name = "birthdays-rss"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.32"
dotenv = "0.15.0"
simple-xml-builder = "1.1.0"
